## Login with Facebook [/api/v1/user/facebook]

### Login with Facebook [POST]


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com


    + Body

            {
              "user":
                {
                  "id": 366,
                  "email": "test@facebook.com",
                  "first_name": "Test",
                  "last_name": "test",
                  "username": "",
                  "provider": "facebook",
                  "uid": "1234567890"
                }
            }