Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - spec/**/*
    - 'lib/rails-base/features.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24
  Exclude:
    - 'lib/rails-base/features.rb'

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - 'lib/rails-base/features.rb'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'lib/templates/**/*.rb'

Style/InitialIndentation:
  Exclude:
    - 'lib/templates/**/*.rb'

Style/SymbolArray:
  Exclude:
    - 'lib/templates/**/add_*.rb'

Style/ModuleFunction:
  Enabled: false

AllCops:
  Exclude:
    - 'lib/templates/chat/migration-models/user.rb'
    - 'lib/templates/chat/routes.rb'
    - 'lib/templates/chat/routes_2.rb'
    - 'lib/templates/chat/sessions_controller.rb'
    - 'lib/templates/chat/specs/rails_helper.rb'
